### ISSUE TITLE
Error saying "href="/onboarding/personaldetails" role="tab" routerlinkactive="active">...</a> is not clickable at point (178, 237). Other element would receive the click: <li class="onboarding-tabs personal-details-tab unaccessable inactive" role="presentation">"

### ISSUE THREAD

**Issue by Mundepi28** [tabhresh/Edureka_27Aug#2]
Hi Abhresh,

As we discussed this morning I am getting below error at line number 102. Can you please check and run this code.

Note:- Need to provide your password while login to Edureka.

Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Element <a aria-controls="personalDetails" class="success active-link" data-toggle="tab" href="/onboarding/personaldetails" role="tab" routerlinkactive="active">...</a> is not clickable at point (178, 237). Other element would receive the click: <li class="onboarding-tabs personal-details-tab unaccessable inactive" role="presentation">

**Comment by Mundepi28** [comment]
Added code here:


package com.edureka;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

public class WebPageControls_2_ProfessionalDetails {

    WebDriver driver;
    WebDriverWait wait;

    public void launchEdureka() {

        //Launching chrome browser
        System.setProperty("webdriver.chrome.driver", ".//driver_executables/chromedriver");
        driver = new ChromeDriver();


        //initializing explicit wait
        wait = new WebDriverWait(driver, 10);


        //Navigating to Edureka website
        driver.get("https://www.edureka.co");
        driver.manage().window().maximize();
    }

    public void LogIn() {

        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log In"))).click();
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("inputName"))).sendKeys("mundepi28@gmail.com");

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("pwd1"))).sendKeys("provideYourPassword");
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//button[contains(text(),'LOGIN')]"))).click();

    }

    public void ProfileDetails() {

        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("(//span[@class='webinar-profile-name'])[1]"))).click();
        driver.findElement(By.xpath("(//a[contains(text(),'My Profile')])[1]")).click();
    }

    public void updateProfessionalDetails() {

        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[@id='professional_details']"))).click();

        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        //entering company name
        WebElement companyName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@placeholder='Enter Company Name']")));
        companyName.clear();
        companyName.sendKeys("Omegapoint AB");

        //entering industry
        WebElement industryList = driver.findElement(By.xpath("//select[@name='currentIndustry']"));
        Select myindustry = new Select(industryList);
        myindustry.selectByIndex(2);


        //entering skills
        WebElement skills = driver.findElement(By.xpath("//input[@placeholder='Enter skills (separated by commas)']"));
        skills.clear();
        skills.sendKeys("Automation Testing");

        //current job option
        WebElement currentJobs = driver.findElement(By.xpath("//select[@name='currentjob']"));
        Select myJob = new Select(currentJobs);
        myJob.selectByIndex(3);

        //entering linkdn profile
        WebElement linkdn = driver.findElement(By.xpath("//input[@placeholder='https://linkedin.com/']"));
        linkdn.clear();
        linkdn.sendKeys("https://www.linkedin.com/in/prashant-mundepi-32a8684a");

    }

    public void submitProfessionlaDetails() {

        driver.findElement(By.xpath("//button[contains(text(),'Next')]")).click();

    }

    public void personalDetails() {

        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[@href='/onboarding/personaldetails']"))).click();
    }

    public void logOut() {

        driver.navigate().to("https://www.edureka.co");
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("(//span[@class='webinar-profile-name'])[1]"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log Out"))).click();

    }

    public void closeBrowser() {

        driver.close();
    }

    public static void main(String[] args){

        WebPageControls_2_ProfessionalDetails obj = new WebPageControls_2_ProfessionalDetails();
        obj.launchEdureka();
        obj.LogIn();
        obj.ProfileDetails();
        obj.updateProfessionalDetails();
        obj.submitProfessionlaDetails();
        obj.personalDetails();
        obj.logOut();
        obj.closeBrowser();


    }
}

**Comment by Mundepi28** [comment]
Added code here:

package com.edureka;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

public class WebPageControls_2_ProfessionalDetails {

    WebDriver driver;
    WebDriverWait wait;

    public void launchEdureka() {

        //Launching chrome browser
        System.setProperty("webdriver.chrome.driver", ".//driver_executables/chromedriver");
        driver = new ChromeDriver();


        //initializing explicit wait
        wait = new WebDriverWait(driver, 10);


        //Navigating to Edureka website
        driver.get("https://www.edureka.co");
        driver.manage().window().maximize();
    }

    public void LogIn() {

        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log In"))).click();
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("inputName"))).sendKeys("provideYourUserName");

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("pwd1"))).sendKeys("provideYourPassword");
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//button[contains(text(),'LOGIN')]"))).click();

    }

    public void ProfileDetails() {

        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("(//span[@class='webinar-profile-name'])[1]"))).click();
        driver.findElement(By.xpath("(//a[contains(text(),'My Profile')])[1]")).click();
    }

    public void updateProfessionalDetails() {

        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[@id='professional_details']"))).click();

        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        //entering company name
        WebElement companyName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@placeholder='Enter Company Name']")));
        companyName.clear();
        companyName.sendKeys("Omegapoint AB");

        //entering industry
        WebElement industryList = driver.findElement(By.xpath("//select[@name='currentIndustry']"));
        Select myindustry = new Select(industryList);
        myindustry.selectByIndex(2);


        //entering skills
        WebElement skills = driver.findElement(By.xpath("//input[@placeholder='Enter skills (separated by commas)']"));
        skills.clear();
        skills.sendKeys("Automation Testing");

        //current job option
        WebElement currentJobs = driver.findElement(By.xpath("//select[@name='currentjob']"));
        Select myJob = new Select(currentJobs);
        myJob.selectByIndex(3);

        //entering linkdn profile
        WebElement linkdn = driver.findElement(By.xpath("//input[@placeholder='https://linkedin.com/']"));
        linkdn.clear();
        linkdn.sendKeys("https://www.linkedin.com/in/prashant-mundepi-32a8684a");

    }

    public void submitProfessionlaDetails() {

        driver.findElement(By.xpath("//button[contains(text(),'Next')]")).click();

    }

    public void personalDetails() {

        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[@href='/onboarding/personaldetails']"))).click();
    }

    public void logOut() {

        driver.navigate().to("https://www.edureka.co");
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("(//span[@class='webinar-profile-name'])[1]"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log Out"))).click();

    }

    public void closeBrowser() {

        driver.close();
    }

    public static void main(String[] args){

        WebPageControls_2_ProfessionalDetails obj = new WebPageControls_2_ProfessionalDetails();
        obj.launchEdureka();
        obj.LogIn();
        obj.ProfileDetails();
        obj.updateProfessionalDetails();
        obj.submitProfessionlaDetails();
        obj.personalDetails();
        obj.logOut();
        obj.closeBrowser();


    }
}

**Comment by Mundepi28** [comment]
Error lies in method: public void personalDetails() - line number 102

**Comment by AbhreshSugandhi** [comment]
Hi,
I went through the code and tried running it but since my profile options are different then yours so couldn't run all parts, here are some suggestions which could resolve issues:
1) As I have said not to use wait commands unless required where as ur script is more of waits  less of execution reduce the wait commands and implement implicitly wait and page load waits at respective locations.
2) Use default xpath that you are getting it from the web browser instead of customized on (replace them later if successful with the execution as a whole)
3) I tried running without
     //obj.updateProfessionalDetails();
    //obj.submitProfessionlaDetails();
    //obj.personalDetails();
its working fine.
4) Your Page load is also creating issue as some time the page is getting loaded fast and sometimes slow which is making things fail.
5) Try creating this same example with simple methods that we use in class and skip try catch for this example.
6) The script we can run and see it in the next class I will watch it in ur system as my user profile is different.

Try these and see if it helps or else will take it at the end of the class tomorrow.

Regards,
Abhresh

**Comment by Mundepi28** [comment]
Hi Abhresh,

I did some work arounds as you said like removed explicit wait and using only pageLoadTimeOut and Implicit wait. I have to use unfortunately at some parts the thread.sleep like in login time or between sending user name and password(else it enters partial text sometimes and login fails). Here is mu new code, can you have a look.

**Comment by Mundepi28** [comment]
package com.edureka;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

public class WebPageControls_2_ProfessionalDetails_Dup {

    WebDriver driver;
   // WebDriverWait wait;

    public void launchEdureka() {

        //Launching chrome browser
        System.setProperty("webdriver.chrome.driver", ".//driver_executables/chromedriver");
        driver = new ChromeDriver();

        //pageLoadTimeout and  implicit wait
        driver.manage().timeouts().pageLoadTimeout(10,TimeUnit.SECONDS);
        driver.manage().timeouts().implicitlyWait(5,TimeUnit.SECONDS);


        //initializing explicit wait
      //  wait = new WebDriverWait(driver, 10);


        //Navigating to Edureka website
        driver.get("https://www.edureka.co");
        driver.manage().window().maximize();
    }

    public void LogIn() {

        driver.findElement(By.linkText("Log In")).click();

        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        driver.findElement(By.id("inputName")).sendKeys("Your userName");

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.id("pwd1")).sendKeys("Your password");

        driver.findElement(By.xpath("//button[contains(text(),'LOGIN')]")).click();

    }

    public void ProfileDetails() {

        driver.manage().timeouts().pageLoadTimeout(10,TimeUnit.SECONDS);

        driver.findElement(By.xpath("(//span[@class='webinar-profile-name'])[1]")).click();
        driver.findElement(By.xpath("(//a[contains(text(),'My Profile')])[1]")).click();
    }

    public void updateProfessionalDetails() {

        driver.findElement(By.xpath("//a[@id='professional_details']")).click();

        //entering company name
        WebElement companyName = driver.findElement(By.xpath("//input[@placeholder='Enter Company Name']"));
        companyName.clear();
        companyName.sendKeys("Omegapoint AB");

        //entering industry
        WebElement industryList = driver.findElement(By.xpath("//select[@name='currentIndustry']"));
        Select myindustry = new Select(industryList);
        myindustry.selectByIndex(2);


        //entering skills
        WebElement skills = driver.findElement(By.xpath("//input[@placeholder='Enter skills (separated by commas)']"));
        skills.clear();
        skills.sendKeys("Automation Testing");

        //current job option
        WebElement currentJobs = driver.findElement(By.xpath("//select[@name='currentjob']"));
        Select myJob = new Select(currentJobs);
        myJob.selectByIndex(3);

        //entering linkdn profile
        WebElement linkdn = driver.findElement(By.xpath("//input[@placeholder='https://linkedin.com/']"));
        linkdn.clear();
        linkdn.sendKeys("https://www.linkedin.com/in/prashant-mundepi-32a8684a");

    }

    public void submitProfessionlaDetails() {

        driver.findElement(By.xpath("//button[contains(text(),'Next')]")).click();

    }

    public void personalDetails() {

        driver.findElement(By.xpath("//*[@id=\"onboarding\"]/div/div[1]/div[1]/app-onboarding-leftnav/ul/li[2]/a")).click();

    }

  /*  public void logOut() {

        driver.navigate().to("https://www.edureka.co");
        driver.findElement(By.xpath("(//span[@class='webinar-profile-name'])[1]")).click();
        driver.findElement(By.linkText("Log Out")).click();

    }*/

    public void closeBrowser() {

        driver.close();
    }

    public static void main(String[] args){

        WebPageControls_2_ProfessionalDetails_Dup obj = new WebPageControls_2_ProfessionalDetails_Dup();
        obj.launchEdureka();
        obj.LogIn();
        obj.ProfileDetails();
        obj.updateProfessionalDetails();
        obj.submitProfessionlaDetails();
        obj.personalDetails();
    //    obj.logOut();
      //  obj.closeBrowser();


    }
}

**Comment by AbhreshSugandhi** [comment]
We will check it in ur system at the end of the class

**Comment by Mundepi28** [comment]
Closing this one as I got the workaround to work with this issue, thanks for your time!
