### ISSUE TITLE
Click on Hyperlink

### ISSUE THREAD

**Issue by Devasish82** [tabhresh/Edureka_27Aug#3]
Can anyone please advise, how to click 1st/2nd hyperlink in a webpage without knowing what is this? may be, thru index..but cannt figure out myself.  I could think of following that didn't actually work:

//WebElement Lnk = driver.findElement(By.tagName("a href"));
//Lnk.click();//Work in Progress

Use Case is - Click anything on Google and open the 1st/2nd link that gets available

**Comment by AbhreshSugandhi** [comment]
`package module5;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Iterator;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Linkchecker {
    
    private static WebDriver driver;

    public static void main(String[] args) {
        
        String homePage = "https://www.google.com";
        String url = "";
        HttpURLConnection huc = null;
        int respCode = 200;
 
        System.setProperty("webdriver.chrome.driver", "D:\\Training\\Installation stuff\\Exe Files\\chromedriver.exe");
		driver = new ChromeDriver();
        
        driver.get(homePage);
        
        List<WebElement> links = driver.findElements(By.tagName("a"));
        
        Iterator<WebElement> it = links.iterator();
        
        while(it.hasNext()){
            
            url = it.next().getAttribute("href");
            
            System.out.println(url);
        
            if(url == null || url.isEmpty()){
System.out.println("URL is either not configured for anchor tag or it is empty");
                continue;
            }
            
            if(!url.startsWith(homePage)){
                System.out.println("URL belongs to another domain, skipping it.");
                continue;
            }
            
            try {
                huc = (HttpURLConnection)(new URL(url).openConnection());
                
                huc.setRequestMethod("HEAD");
                
                huc.connect();
                
                respCode = huc.getResponseCode();
                
                if(respCode >= 400){
                    System.out.println(url+" is a broken link");
                }
                else{
                    System.out.println(url+" is a valid link");
                }
                    
            } catch (MalformedURLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        
        driver.quit();

    }
}`

**Comment by AbhreshSugandhi** [comment]
Check your project. added your required files
