### ISSUE TITLE
Not able to click on the search icon for the search bar on the main page of the Edureka website

### ISSUE THREAD

**Issue by deeptikapahi2006** [tabhresh/Edureka_27Aug#4]
code - 
driver.findElement(By.id("homeSearchBar")).sendKeys("Selenium");
		driver.findElement(By.id("homeSearchBarIcon")).click();

Using the above code.
exception:
Exception in thread "main" org.openqa.selenium.ElementNotVisibleException: element not visible
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 100 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'HP1', ip: '192.168.225.41', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:51139}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e), userDataDir=C:\Users\HP\AppData\Local\Temp\scoped_dir32692_6127}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=68.0.3440.106, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: 801b61b8f1badbde0eca5f900bb8ab2a
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
	at assignment2.Assign2.main(Assign2.java:55)

**Comment by Mundepi28** [comment]
Might be issue with you synchronisation, please provide your piece of code you're using, I used the below code, maybe it will help you!

public void locatorById() {

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("homeSearchBar"))).sendKeys("Search for a Course");

        wait.until(ExpectedConditions.elementToBeClickable(By.id("homeSearchBarIcon"))).click();

    }

**Comment by jsindhukilari** [comment]
> code -
> driver.findElement(By.id("homeSearchBar")).sendKeys("Selenium");
> driver.findElement(By.id("homeSearchBarIcon")).click();
> 
> Using the above code.
> exception:
> Exception in thread "main" org.openqa.selenium.ElementNotVisibleException: element not visible
> (Session info: chrome=68.0.3440.106)
> (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 100 milliseconds
> Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
> System info: host: 'HP1', ip: '192.168.225.41', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_65'
> Driver info: org.openqa.selenium.chrome.ChromeDriver
> Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:51139}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e), userDataDir=C:\Users\HP\AppData\Local\Temp\scoped_dir32692_6127}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=68.0.3440.106, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
> Session ID: 801b61b8f1badbde0eca5f900bb8ab2a
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> at java.lang.reflect.Constructor.newInstance(Unknown Source)
> at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
> at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
> at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
> at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
> at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
> at assignment2.Assign2.main(Assign2.java:55)

Hi Deepthi,

Looks like a synchronization error. I faced this. We need to implement appropriate pageload and wait commands.
Try the below code. This is working in mine.

public void loginAndSearchEdureka() 
 {
		
// Initialize Firefox Browser driver object
		
		System.setProperty("webdriver.chrome.driver","/Users/vijayravichandran/Sindhu/Edureka_Installation/Exec files/chromedriver");
		
WebDriver driver=new ChromeDriver();
		
//  Wait for the page to load completely
		driver.manage().window().maximize();
		driver.manage().deleteAllCookies(); 
		driver.manage().timeouts().pageLoadTimeout(15,TimeUnit.SECONDS); 
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
//Launch the Edureka website
		driver.get("https://www.edureka.co/");
		
//Enter "Selenium" manually in the Input field  
		
		driver.findElement(By.xpath("//input[@id='homeSearchBar']")).sendKeys("Selenium");
		WebDriverWait wait=new WebDriverWait(driver,20);
		
//Click the search icon to search for relevant courses
		
WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id='homeSearchBarIcon']")));
       element.click();
driver.manage().timeouts().pageLoadTimeout(10,TimeUnit.SECONDS); driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
}

**Comment by deeptikapahi2006** [comment]
Thanks Guys...:)
