### ISSUE TITLE
Issue to upload a file using sikuli in maven framework

### ISSUE THREAD

**Issue by Mundepi28** [tabhresh/Edureka_27Aug#7]
Hi, 
I have written a code using sikuli to open a file, but the file is not selected. There are two main action:-
1. Select a file
2. and then click on open button(No file path action)

Here's my code:-

public void picSelect() throws FindFailed {

        Screen s = new Screen();

        Pattern Open = new Pattern("/Users/Open.jpg");

        s.type("/Users/MyPic.jpg");

        s.click(Open);

    }

**Comment by AbhreshSugandhi** [comment]
check with complete path!

**Comment by Mundepi28** [comment]
Hi,
I guess its full only, in Mac its like this.
Is this below line correct because I am trying to select the image just and not typing the path name as we did in the class demo. I have only one argument here that is to select the image just.

s.type("/Users/MyPic.jpg");

**Comment by AbhreshSugandhi** [comment]
It should be like this:

Screen s = new Screen();
    Pattern Open = new Pattern("/Users/Open.jpg");
    Pattern Type = new Pattern("/Users/MyPic.jpg");
    s.type(Type, "What you want to type put it here");
    s.click(Open);
}


This is a correct way to do it!

**Comment by jsindhukilari** [comment]
Abhresh,
 In Mac, we dont have the option to enter the path of the file using s.type().
I tried to crop the icons in the fileopen dialog box and tried opening it using Pattern
It din't work! 
May be in Windows, its quite easier and straightforward.
