### ISSUE TITLE
Did anyone tried the Check- Enter pincode for Delivery option in flipkart

### ISSUE THREAD

**Issue by jsindhukilari** [tabhresh/Edureka_27Aug#8]
Hi Team,

Facing issue in step 4 while trying to do the following:
1.Open flipkart
2.Search for selenium book
3.Select selelnium book
4.Click on Check button or try to enter pincode manually in the input field.

I tried applying waits, thread.sleep, scroll into view, refreshing the page, etc.
Nothing worked out.
I tried to click on the shopping cart still it dint work. Please suggest your inputs.
Here is the code: 

     
		//By loc_shopping_cart=By.xpath("//*[@id='container']/div/header/div[1]/div/div/div/div[3]/a/div/span");
		By loc_pincode_input=By.xpath("//input[@id='pincodeInputId']");
		By loc_check_button=By.xpath("//span[contains(text(),'Check')]");
		//By loc_check_button=By.xpath("//*[@class='_3VH2pM']//following::span[1]");

	public void check_delivery_area(int pincode) throws InterruptedException
	{
		System.out.println("Inside");--Code works fine until here
		wait_var=new WebDriverWait(driver,20);
		WebElement ele_check=wait_var.until
                           (ExpectedConditions.visibilityOfElementLocated(loc_check_button));
		ele_check.click();
		Thread.sleep(2000);
		System.out.println("check link clicked");
		
		driver.findElement(loc_pincode_input).sendKeys(String.valueOf(pincode));	
		Thread.sleep(2000);
       }

**Comment by Mundepi28** [comment]
Hi Sindhu,

When you search for the selenium course, it opens a new window so you need to handle the driver to work on the new opened window. So, if you change the focus of driver to new window, your code will work. I have used the below code and it worked for me, you can refer to it and get an idea.


Test(priority = 1)                     //searching selenium book
    public void searchSeleniumBook() {

        Actions act_book = new Actions(driver);
        act_book.moveToElement(driver.findElement(By.xpath("//input[@name='q']"))).click().sendKeys("Selenium book").build().perform();
        act_book.moveToElement(driver.findElement(By.xpath("//button[@type='submit']"))).click().build().perform();
        act_book.moveToElement(driver.findElement(By.xpath("//div[@data-id='9781782168850']"))).click().build().perform();
    }

    @Test(dependsOnMethods = {"searchSeleniumBook"})
    public void pinCodeAndDurationCheck() throws IOException {

        //switching to new window and performing actions there

        String parentHandle = driver.getWindowHandle();
        System.out.println("********* "+parentHandle);

        Set<String> handles = driver.getWindowHandles();
        System.out.println("********* "+handles);

        for (String winHandle : handles) {

            if (!winHandle.equalsIgnoreCase(parentHandle))
            {
                driver.switchTo().window(winHandle);
                driver.findElement(By.id("pincodeInputId")).sendKeys("248001");     //sending pin code and verifying

                driver.findElement(By.className("_2aK_gu")).click();

                try {
                    Thread.sleep(2000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                String durationTime = driver.findElement(By.xpath("//div[@class='_29Zp1s']")).getText();
                System.out.println("Delivery time is "+durationTime);

                if (durationTime.contains("Delivery in2-3 weeks"))           //verifying duration text
                {
                    System.out.println("Delivery possible");
                }
                else
                {
                    System.out.println("Delivery not possible");
                }

**Comment by jsindhukilari** [comment]
Thanks prashant. Edureka support team also said the same to try with window handles. It worked for me finally.
